version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"  # Backend port
      - "5173:5173"  # Frontend port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 